### ISSUE TITLE
make *everything* more ES2015

### ISSUE THREAD

**Issue by jakeburden** [dsurgeons/OpenShare#1]
example: [`var`](https://github.com/dsurgeons/OpenShare/search?utf8=%E2%9C%93&q=var) should be `let` or `const`.

**Comment by iswanj** [comment]
@jekrb I'd like to work on this.

**Comment by jakeburden** [comment]
Greetings @iswanj 👋👋

Great! Checkout these contributing guidelines if you need too.  Would love to have your help on this 🌴

https://github.com/OpenShare/openshare/wiki/6.-Contributing

Let me know if you have any questions :)

**Comment by iswanj** [comment]
:+1:

**Comment by jakeburden** [comment]
Hey @iswanj how is it going?  Just wondering if you have any questions.  No rush 👍

**Comment by iswanj** [comment]
@jekrb little bit busy.. with office works, will do it on this weekend :+1:

**Comment by iswanj** [comment]
@jekrb Add eslint for this project, any thoughts...

**Comment by jakeburden** [comment]
@iswanj good idea! I've added it: https://github.com/OpenShare/openshare/commit/512f77b0a507b63f5de7838d974cc156039ead3b

**Comment by jakeburden** [comment]
Closed as of #4 👍
