### ISSUE TITLE
502 Bad Gateway for Twitter count setup

### ISSUE THREAD

**Issue by alexchantastic** [dsurgeons/OpenShare#11]
I am currently getting a 502 Bad Gateway error when attempting to set up the Twitter count app authorization. This occurs on the openshare.social domain after the auth redirect from twitter.com.

**Comment by jakeburden** [comment]
Hey thanks for pointing this out!

I just restarted the server and it seems to work on my end.  Mind giving it another try?

**Comment by alexchantastic** [comment]
Hm... still getting the 502 error on my end. I've tried revoking the app the redoing as well.

**Comment by jakeburden** [comment]
Yikes. My apologies for that.  I'll look deeper into this issue soon.
Thanks for retrying! I'll ping you if I find anything.

Keeping this issue open for now.

**Comment by alexchantastic** [comment]
No problem. Let me know if I can help test further.

**Comment by alexchantastic** [comment]
@jekrb just following up to see if you were able to diagnose this issue yet.

**Comment by jakeburden** [comment]
@alexchantastic I've not had much time to look into this issue yet unfortunately 😞

**Comment by MerlinMason** [comment]
Also getting the same issue 😬

**Comment by alexchantastic** [comment]
Since this hasn't been fixed yet, I've forked the repo and updated the tweet count API to point to use http://newsharecounts.com/.

You can find my fork here: https://github.com/alexchantastic/openshare

**Comment by jakeburden** [comment]
Thank you @alexchantastic for the initiative. Awesome work! 🎉

Would you be willing to discuss how [newsharecounts](http://newsharecounts.com) is getting twitter share data?  You could DM me if you want.

**Comment by alexchantastic** [comment]
@jekrb I don't work for or own newsharecounts, but have used their service when I was rolling my own share library before switching to OpenShare. I assume they are operating similarly to how your service works by using the Twitter search API and caching the number of shares to a given URL.

**Comment by jakeburden** [comment]
@AaronShea found the solution! We hadn't renewed twitter api keys and it was causing a 502 error for new sign ups.

Should be all good now
