### ISSUE TITLE
cdnjs hosting

### ISSUE THREAD

**Issue by sashberd** [dsurgeons/OpenShare#12]
Hi
We would like to [add ](https://github.com/cdnjs/cdnjs/issues/9639)your library to cdnjs hosting

I saw in dist 2 files: openshare.js and test.js. What is for test.js file?
Thanks

**Comment by jakeburden** [comment]
Greetings @sashberd :wave:

The test.js file is just for internal testing.  Only `/dist/openshare.js` would need to be hosted.

Thank you for offering to add openshare to cdnjs, it's greatly appreciated!

**Comment by sashberd** [comment]
The PR was opened. FYR https://github.com/cdnjs/cdnjs/pull/12207
